'''
Generates a zip that contains the core files the compilation programs need
This includes headers, libraries, and of course SplashKit
'''
import shutil
import os
import sys
import io
import zipfile

splashkit_library_path = sys.argv[1]
splashkit_includes_path = sys.argv[2]
sysroot_path = sys.argv[3]
output_archive_path = sys.argv[4]

assert sys.argv[5]=="stored" or sys.argv[5] == "compressed"
compression = zipfile.ZIP_DEFLATED if sys.argv[5] == "compressed" else zipfile.ZIP_STORED

in_memory_in_place = compression != zipfile.ZIP_STORED # we can't do this in place anymore, since the original zip may already be compresed

splashkit_sysroot_library_path = "lib/"
splashkit_sysroot_includes_path = "include/splashkit/"

try:
    with open(sysroot_path, 'rb') as f:
        original_zip_content = f.read()
except:
    sys.exit("\033[91mFailed to read in system root prebuilt zip file at "+sysroot_path+"\033[0m")


def copy_in_file(new_zip, filename, newfilename):
    with open(filename, 'rb') as f:
        file_content = f.read()
    new_zip.writestr(newfilename, file_content)

with io.BytesIO() as new_zip_buffer:
    # start by copying the original system root zip into memory
    new_zip_buffer.write(original_zip_content)

    # access it as a zip, and add files to it
    with zipfile.ZipFile(new_zip_buffer, 'a', compression=compression) as original_zip:

        # are we doing this in place?
        if in_memory_in_place:
            new_zip = original_zip
        else:
            new_zip = zipfile.ZipFile(output_archive_path, mode='w', compression=compression)
            # if not, copy in the original files
            for file in original_zip.namelist():
                new_zip.writestr(file, original_zip.read(file));


        copy_in_file(new_zip, splashkit_library_path, splashkit_sysroot_library_path+"libSplashKitBackend.a");


        global_header = "// autogenerated by cxx_backend_systemroot_builder.py - will be overwritten easily!\n"
        global_header += "// all SplashKit includes:\n"

        for file in os.listdir(splashkit_includes_path):
            if ".h" in file and 'raspi_gpio' not in file:
                copy_in_file(new_zip, splashkit_includes_path+file, splashkit_sysroot_includes_path+file);

                global_header += "#include \"splashkit/"+file+"\"\n"

        global_header += """
        // mimic namespacelessness of normal SplashKit Clib-based C++ version
        using namespace splashkit_lib;
        """

        new_zip.writestr("include/splashkit.h", global_header)

    new_zip_buffer.seek(0)

    if in_memory_in_place:
        # now write it out!
        with open(output_archive_path, 'wb') as f:
            f.write(new_zip_buffer.getvalue())
    else:
        # we already wrote it out!
        pass
