// TODO: This should be automated
let SK;
let clear_screen;
let open_window;
let refresh_screen;
let rgba_color_from_double;
let fill_ellipse;
let fill_rectangle;
let fill_triangle;
let process_events;
let any_key_pressed;
let key_down;
let write_line;
let mouse_position;
let QUOTE_ENTER;
let W_KEY;
let A_KEY;
let S_KEY;
let D_KEY;
let LEFT_BUTTON;
let mouse_clicked;
let mouse_down;

moduleEvents.addEventListener("onRuntimeInitialized", function() {
    SK = new Module.SplashKitJavascript();
    clear_screen = SK.clear_screen;
    open_window = SK.open_window;
    refresh_screen = SK.refresh_screen;
    rgba_color_from_double = SK.rgba_color_from_double;
    fill_ellipse = SK.fill_ellipse;
    fill_rectangle = SK.fill_rectangle;
    fill_triangle = SK.fill_triangle;
    process_events = SK.process_events;
    any_key_pressed = SK.any_key_pressed;
    key_down = SK.key_down;
    write_line = SK.write_line;
    mouse_position = SK.mouse_position;
    QUOTE_ENTER = Module.QUOTE_ENTER;
    W_KEY = Module.W_KEY;
    A_KEY = Module.A_KEY;
    S_KEY = Module.S_KEY;
    D_KEY = Module.D_KEY;
    LEFT_BUTTON = Module.LEFT_BUTTON;
    mouse_clicked = SK.mouse_clicked;
    mouse_down = SK.mouse_down;
});